name: Autopkg run

on:
  watch:
    types: [started]
  # Commenting out the automated schedule so this AutoPKG build doesn't run on its own.
  # Keep this part in to run on a set schedule
  schedule: 
     - cron: 00 14 * * 1-5
  workflow_dispatch: # manually triggered
    inputs:
      recipe:
        description: Optional recipe to run (e.g. Google/GoogleChrome-test.jamf.recipe.yaml)
        required: false
      debug:
        description: Enable debug
        required: false
        default: 'False'
        type: choice
        options:
        - 'False'
        - 'True'

jobs:
  AutoPkg:
    runs-on: macos-latest
    timeout-minutes: 90 # Keeps your builds from running too long
    env:
      AUTOPKG_SHA256: "304f51506103b5daae44a977df9f53c0ee43f164813690b674b1d1437c833b03"
      AUTOPKG_URL: "https://github.com/autopkg/autopkg/releases/download/v2.7.6/autopkg-2.7.6.pkg"
      GITHUB_TOKEN: ${{ secrets.AUTOPKG_RUNNER_GITHUB_TOKEN }}
      FLEET_GITOPS_GITHUB_TOKEN: ${{ secrets.FLEET_GITOPS_GITHUB_TOKEN }}
      FLEET_API_BASE: ${{ secrets.FLEET_API_BASE }}
      FLEET_API_TOKEN: ${{ secrets.FLEET_API_TOKEN }}
      FLEET_TEAM_ID: ${{ secrets.FLEET_TEAM_ID }}
      FLEET_GITOPS_REPO_URL: ${{ secrets.FLEET_GITOPS_REPO_URL }}
      FLEET_GITOPS_AUTHOR_EMAIL: ${{ secrets.FLEET_GITOPS_AUTHOR_EMAIL }}
      FLEET_TEAM_YAML_PATH: ${{ secrets.FLEET_TEAM_YAML_PATH }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_CLOUDFRONT_DOMAIN: ${{ secrets.AWS_CLOUDFRONT_DOMAIN }}
    steps:
    - name: Checkout AutoPkg recipes
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 #v3.5.3 Pin SHA1 hash instead of version
      with:
        token: ${{ env.GITHUB_TOKEN }}
        fetch-depth: 1
    - name: Setup Python
      uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 #v4.7.0
      with:
        python-version: 3.11

    - name: Install Python dependencies #(remove pyyaml line if you don't use yaml recipes)
      run: |
        pip3 install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install pyyaml

    - name: Install AutoPkg
      run: |
        curl -L ${{ env.AUTOPKG_URL }} --output /tmp/autopkg.pkg
        echo "${{ env.AUTOPKG_SHA256 }} */tmp/autopkg.pkg" | shasum -c
        if [[ $? != "0" ]]; then exit 1; fi
        sudo installer -pkg /tmp/autopkg.pkg -target /
        
    - name: Install boto3 for AutoPkg's Python
      run: |
        # AutoPkg bundles its own Python framework
        # Find AutoPkg's Python and install boto3 there
        AUTOPKG_PYTHON="/Library/AutoPkg/Python3/Python.framework/Versions/Current/bin/python3"
        
        if [ -f "$AUTOPKG_PYTHON" ]; then
          echo "Installing boto3 using AutoPkg's bundled Python: $AUTOPKG_PYTHON"
          sudo "$AUTOPKG_PYTHON" -m pip install --upgrade pip
          sudo "$AUTOPKG_PYTHON" -m pip install boto3
        else
          echo "AutoPkg Python not found at $AUTOPKG_PYTHON, trying system Python"
          sudo /usr/bin/python3 -m pip install --upgrade pip
          sudo /usr/bin/python3 -m pip install boto3 2>/dev/null || \
            sudo /usr/bin/python3 -m pip install --break-system-packages boto3
        fi

    - name: Install certifi and set CA bundle
      run: |
        python -m pip install --upgrade certifi
        SSL_CERT_FILE=$(python -m certifi)
        echo "SSL_CERT_FILE=$SSL_CERT_FILE" >> "$GITHUB_ENV"
        echo "REQUESTS_CA_BUNDLE=$SSL_CERT_FILE" >> "$GITHUB_ENV"

    - name: Verify HTTPS connectivity
      run: |
        python - <<'PY'
        import ssl, urllib.request
        ctx = ssl.create_default_context(cafile=ssl.get_default_verify_paths().openssl_cafile)
        try:
            urllib.request.urlopen("https://fleet.kitzy.net", context=ctx)
        except Exception as e:
            print(f"HTTPS connectivity test failed: {e}")
            raise
        else:
            print("HTTPS connectivity verified")
        PY

    - name: Configure AutoPkg and Git
      run: |
        # Explicitly mask only the sensitive tokens
        echo "::add-mask::${{ secrets.FLEET_API_TOKEN }}"
        echo "::add-mask::${{ secrets.FLEET_GITOPS_GITHUB_TOKEN }}"
        echo "::add-mask::${{ secrets.GITHUB_TOKEN }}"
        echo "::add-mask::${{ secrets.AWS_ACCESS_KEY_ID }}"
        echo "::add-mask::${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        
        defaults write com.github.autopkg RECIPE_OVERRIDE_DIRS "$(pwd)"/overrides/
        defaults write com.github.autopkg FAIL_RECIPES_WITHOUT_TRUST_INFO -bool YES
        defaults write com.github.autopkg GITHUB_TOKEN "${{ secrets.GITHUB_TOKEN }}"
        defaults write com.github.autopkg FLEET_GITOPS_GITHUB_TOKEN "${{ secrets.FLEET_GITOPS_GITHUB_TOKEN }}"
        defaults write com.github.autopkg FLEET_API_TOKEN "${{ secrets.FLEET_API_TOKEN }}"
        
        # Configure Fleet environment variables for AutoPkg
        defaults write com.github.autopkg FLEET_API_BASE "$FLEET_API_BASE"
        defaults write com.github.autopkg FLEET_TEAM_ID "$FLEET_TEAM_ID"
        defaults write com.github.autopkg FLEET_GITOPS_REPO_URL "$FLEET_GITOPS_REPO_URL"
        defaults write com.github.autopkg FLEET_GITOPS_AUTHOR_EMAIL "$FLEET_GITOPS_AUTHOR_EMAIL"
        defaults write com.github.autopkg FLEET_TEAM_YAML_PATH "$FLEET_TEAM_YAML_PATH"
        
        # Configure AWS environment variables for AutoPkg
        defaults write com.github.autopkg AWS_ACCESS_KEY_ID "$AWS_ACCESS_KEY_ID"
        defaults write com.github.autopkg AWS_SECRET_ACCESS_KEY "$AWS_SECRET_ACCESS_KEY"
        defaults write com.github.autopkg AWS_S3_BUCKET "$AWS_S3_BUCKET"
        defaults write com.github.autopkg AWS_CLOUDFRONT_DOMAIN "$AWS_CLOUDFRONT_DOMAIN"
        
        git config --global user.name "runner"
        git config --global user.email "runner@githubactions.local"

    - name: Add AutoPkg repos
      run: |
        for repo in $(cat repo_list.txt); do autopkg repo-add "$repo"; done

    - name: Debug Environment Variables
      run: |
        echo "FLEET_API_BASE is configured"
        echo "FLEET_TEAM_ID is configured"
        echo "FLEET_GITOPS_REPO_URL is configured"
        echo "FLEET_GITOPS_AUTHOR_EMAIL is configured"
        echo "FLEET_TEAM_YAML_PATH is configured"
        echo "AWS_S3_BUCKET is configured"
        echo "AWS_CLOUDFRONT_DOMAIN is configured"
        # Don't echo sensitive tokens, just check if they're set
        echo "FLEET_API_TOKEN set: $([[ -n $FLEET_API_TOKEN ]] && echo 'YES' || echo 'NO')"
        echo "FLEET_GITOPS_GITHUB_TOKEN set: $([[ -n $FLEET_GITOPS_GITHUB_TOKEN ]] && echo 'YES' || echo 'NO')"
        echo "AWS_ACCESS_KEY_ID set: $([[ -n $AWS_ACCESS_KEY_ID ]] && echo 'YES' || echo 'NO')"
        echo "AWS_SECRET_ACCESS_KEY set: $([[ -n $AWS_SECRET_ACCESS_KEY ]] && echo 'YES' || echo 'NO')"

    - name: Run AutoPkg
      continue-on-error: true
      id: autopkg_run
      run: |
        # Run from /tmp so the workspace isn't on sys.path for the AutoPkg subprocess
        cd /tmp
        python3 "$GITHUB_WORKSPACE/autopkg_tools.py" -l "$GITHUB_WORKSPACE/recipe_list.json"
        # Export PR artifacts and also copy them into the workspace for downstream steps
        if [ -f pull_request_title ]; then
          cp pull_request_title "$GITHUB_WORKSPACE/"
          cp pull_request_body "$GITHUB_WORKSPACE/"
          echo "TITLE=$(cat pull_request_title)" >> $GITHUB_ENV
          echo "BODY<<EOF" >> $GITHUB_ENV
          cat pull_request_body >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        fi
      env:
        RECIPE: ${{ github.event.inputs.recipe }}
        SLACK_WEBHOOK_URL: None

    - name: Create Trust Info pull request
      if: ${{ hashFiles('pull_request_title') != '' }}
      id: create_pr
      run: |
        export BRANCH_NAME=trust-info-`date +'%Y-%m-%d-%H%M%S'`
        git checkout -b $BRANCH_NAME
        git add overrides/
        git commit -m "$TITLE"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
        git push --force --set-upstream origin $BRANCH_NAME
        PR_RESPONSE=$(jq -n --arg title "$TITLE" \
              --arg body "$BODY" \
              --arg head "$BRANCH_NAME" \
           '{title: $title, body: $body, head: $head, "base": "${{ github.ref_name }}"}' | curl -s --request POST \
           --url https://api.github.com/repos/${{ github.repository }}/pulls \
           --header "authorization: Bearer $GITHUB_TOKEN" \
           --header 'content-type: application/json' \
           -d@-)
        PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.number')
        echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
